# Generated by Django 4.1.2 on 2022-10-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=56)),
                ('name_ru', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('til', models.IntegerField(default=1)),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.category')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('subscribe', models.BooleanField(default=False)),
                ('kurs', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.course')),
            ],
        ),
    ]
