# Generated by Django 4.1.2 on 2022-10-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribe',
        ),
    ]
