# Generated by Django 4.0.6 on 2022-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.IntegerField(null=True),
        ),
    ]
