# Generated by Django 4.0.6 on 2022-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_user_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='chat_id',
            field=models.BigIntegerField(default=5392556467),
        ),
    ]
