# Generated by Django 4.0.6 on 2022-10-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_videos_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ctg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.category'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.course'),
        ),
    ]
